"""Merge human-confirmed scan records into an active-learning ground-truth set.

Pulls records whose raw MRZ a human confirmed/corrected (corrected_mrz IS NOT
NULL) and turns them into ground-truth entries in the SAME format as the hand-
built GroundTruth/ground_truth.json (`{stem: {"format": ..., "lines": [...]}}`).

Safety:
  * Writes to a SEPARATE file GroundTruth/ground_truth_active.json — the golden
    hand-verified ground_truth.json is NEVER touched.
  * Images go to Images/MRZ_Data/Processed_data/images/active/ — the `test/`
    evaluation set is never polluted.
  * Records whose image SHA-256 matches a ground-truth/test image are EXCLUDED
    (data leakage). Reuses _gt_image_hashes from export_dataset.py.
  * Idempotent: re-running rebuilds the active GT from the DB; stems are the
    stable `al_<record_id>` so images/labels line up.

Usage:
    DATABASE_URL=postgres://... python Scripts/active_learning/merge_to_gt.py
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT))

from Scripts.active_learning.export_dataset import _gt_image_hashes, _connect

_ACTIVE_GT_PATH = _ROOT / "GroundTruth" / "ground_truth_active.json"
_ACTIVE_IMG_DIR = _ROOT / "Images" / "MRZ_Data" / "Processed_data" / "images" / "active"

# MRZ line length → format, when the DB row has no explicit mrz_format.
_LEN_TO_FORMAT = {44: "TD3", 36: "TD2", 30: "TD1"}


def _infer_format(mrz_format: str | None, lines: list[str]) -> str:
    if mrz_format in ("TD1", "TD2", "TD3"):
        return mrz_format
    max_len = max((len(str(x)) for x in lines), default=0)
    # Snap to the nearest known length.
    if max_len >= 40:
        return "TD3"
    if max_len >= 33:
        return "TD2"
    return "TD1"


def merge() -> None:
    gt_hashes = _gt_image_hashes()
    print(f"Ground-truth image hashes loaded: {len(gt_hashes)} (excluded from active GT)")

    _ACTIVE_IMG_DIR.mkdir(parents=True, exist_ok=True)

    active_gt: dict[str, dict] = {
        "_meta": {
            "description": "Active-learning ground truth built from human-confirmed "
                           "scan_records (corrected_mrz). Generated by merge_to_gt.py — "
                           "do not hand-edit. The golden set lives in ground_truth.json.",
            "source": "scan_records WHERE corrected_mrz IS NOT NULL",
        }
    }

    query = (
        "SELECT id, image, image_sha256, corrected_mrz, mrz_format "
        "FROM scan_records "
        "WHERE corrected_mrz IS NOT NULL "
        "ORDER BY id"
    )

    written = 0
    skipped_leak = 0
    skipped_bad = 0
    with _connect() as conn:
        for rec_id, image, sha, corrected_mrz, mrz_format in conn.execute(query):
            if sha in gt_hashes:
                skipped_leak += 1
                continue
            lines = [str(x) for x in (corrected_mrz or []) if str(x).strip()]
            if len(lines) < 2:
                skipped_bad += 1
                continue

            stem = f"al_{rec_id}"
            (_ACTIVE_IMG_DIR / f"{stem}.jpg").write_bytes(bytes(image))
            active_gt[stem] = {
                "format": _infer_format(mrz_format, lines),
                "lines": lines,
            }
            written += 1

    _ACTIVE_GT_PATH.write_text(
        json.dumps(active_gt, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print(f"Active GT written: {written} records → {_ACTIVE_GT_PATH}")
    print(f"Images → {_ACTIVE_IMG_DIR}")
    print(f"Excluded (ground-truth leakage): {skipped_leak}")
    print(f"Skipped (fewer than 2 MRZ lines): {skipped_bad}")
    if written == 0:
        print("Note: no confirmed corrected_mrz records yet.")


if __name__ == "__main__":
    merge()
